[package]
name = "clinical_trial_risk"
version = "0.1.0"
edition = "2021"

[lib]
name = "ctre"
path = "src/lib.rs"

[[bin]]
name = "ctre"
path = "src/main.rs"

[dependencies]
num = "0.4.3"
rand = "0.8.5"
statrs = "0.17.1"
